repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
      - id: black
        args: ['-l 120']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        language: python
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        pass_filenames: false
